[package]
name = "bocaboca"
version = "1.0.0"
edition = "2024"
published-at = "0x32d94416d61d92428f25c970485313ca900dc202bb8522e931afbf3231eae408"

[addresses]
bocaboca = "0x32d94416d61d92428f25c970485313ca900dc202bb8522e931afbf3231eae408"
