[package]
name = "lottery"
version = "1.0.0"
edition = "2024"

[dependencies]
bocaboca = { local = "../token" }

[addresses]
lottery = "0x0"
bocaboca = "0x32d94416d61d92428f25c970485313ca900dc202bb8522e931afbf3231eae408"
