[package]
name = "omeone_shared"
version = "1.0.0"
edition = "2024.beta"

[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "framework/testnet" }

[addresses]
omeone = "0x0"
iota = "0x2"

[dev-addresses]
omeone = "0xCAFE"