[package]
name = "recommendation"
version = "1.0.0"
edition = "2024.beta"

[dependencies]
MoveStdlib = { git = "https://github.com/iotaledger/iota", subdir = "crates/iota-framework/packages/move-stdlib", rev = "framework/testnet" }
Iota = { git = "https://github.com/iotaledger/iota", subdir = "crates/iota-framework/packages/iota-framework", rev = "framework/testnet" }

[addresses]
omeone = "0x0"