[package]
name = "recommendation"
version = "1.0.0"
edition = "2024"
published-at = "0x5b27473dad4cff322d5c93b1afe5a128754bd8a4f628d00116e9ae1e680eac8b"

[addresses]
recommendation = "0x5b27473dad4cff322d5c93b1afe5a128754bd8a4f628d00116e9ae1e680eac8b"
