[package]
name = "rewards"
version = "1.0.0"
edition = "2024"
published-at = "0x6af247ddda822ae6d6c51c5b4328db3b26a8f63403f95b03e643c40c1a234a97"

[dependencies]
bocaboca = { local = "../token" }

[addresses]
rewards = "0x6af247ddda822ae6d6c51c5b4328db3b26a8f63403f95b03e643c40c1a234a97"
bocaboca = "0x32d94416d61d92428f25c970485313ca900dc202bb8522e931afbf3231eae408"
