[package]
name = "user_status"
version = "1.0.0"
edition = "2024"
published-at = "0x09b0fc0b5d0ded7ef4bcb437b1a6b9a783f253319c1c166910d33ac60771b3e7"

[addresses]
user_status = "0x09b0fc0b5d0ded7ef4bcb437b1a6b9a783f253319c1c166910d33ac60771b3e7"
