[package]
name = "bounty"
version = "0.1.0"
edition = "2024"

[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "4698c6723208e052a00c74602d2c8dc0efffe5de" }
bocaboca = { local = "../token" }

[addresses]
bounty = "0x0"
