[package]
name = "email_escrow"
version = "1.0.0"
edition = "2024"
published-at = "0x2ae350bdc51818f22f9a198c6ab72ec38efe735ad3007c661cb1591b7ccbbbdb"

[dependencies]
bocaboca = { local = "../token" }

[addresses]
email_escrow = "0x2ae350bdc51818f22f9a198c6ab72ec38efe735ad3007c661cb1591b7ccbbbdb"
bocaboca = "0x32d94416d61d92428f25c970485313ca900dc202bb8522e931afbf3231eae408"
